### ISSUE TITLE
Failed to encode cookie error when using Hapi 13

### ISSUE THREAD

**Issue by mirceaalexandru** [senecajs/seneca-auth#80]
```
Debug: internal, implementation, error 
    Error: Failed to encode cookie (seneca-login) value: Password string too short (min 32 characters required)
    at /Users/mcdonnelldean/repos/vidi-dashboard/node_modules/hapi/node_modules/statehood/lib/index.js:436:34
    at /Users/mcdonnelldean/repos/vidi-dashboard/node_modules/hapi/node_modules/hoek/lib/index.js:850:22
    at doNTCallback0 (node.js:407:9)

```

**Comment by slester** [comment]
Did you ever find a solution to this? It just happened to us as well.
